<?php $title = 'Test Mating' . ($entity->getSire() && $entity->getDam() ? ': ' . $entity->getSire() . ' x ' . $entity->getDam() : ''); ?>
<?php $this->headScript()->appendFile($this->basePath('js/ace-pedigree.js')); ?>
<?php $this->headTitle($title); ?>
<?php $this->pedigree($entity, $maxGen); ?>
<h2 class="page-header"><?= $title ?></h2>

<div class="no-break">
    <?= $this->pedigree() ?>
</div>

<?php if ($entity->getSire() && $entity->getDam()) : ?>
    <div class="no-break">
        <?= $this->pedigree()->analysis() ?>
    </div>
<?php else : ?>
    <div class="modal" id="addAnimal" tabindex="-1" role="dialog" aria-labelledby="addAnimalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addAnimalLabel">Choose a <?= $this->species() ?></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <?php $form->get('q')->setAttribute('data-ajax-url', $this->url('ace-pedigree/animals', ['action' => 'suggest'])) ?>
                    <?= $this->form($form) ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>