<?php $title = 'Test Mating' . ($entity->getSire() && $entity->getDam() ? ': ' . $entity->getSire() . ' x ' . $entity->getDam() : ''); ?>
<?php $this->headTitle($title); ?>
<?php $this->pedigree($entity, $maxGen); ?>
<h2 class="page-header"><?= $title ?></h2>

<div class="no-break">
    <?= $this->pedigree() ?>
</div>

<?php if ($entity->getSire() && $entity->getDam()) : ?>
    <div class="no-break">
        <?= $this->pedigree()->analysis() ?>
    </div>
<?php endif; ?>