<h3>Pedigree</h3>
<div class="container">
    <form class="form-inline">
        <?php if (!$dog->getId()) : ?>
            <input type="hidden" name="sire" value="<?= $dog->getSire()->getId() ?>" />
            <input type="hidden" name="dam" value="<?= $dog->getDam()->getId() ?>" />
        <?php endif; ?>
        Displaying <select class="form-control" id="maxGen" name="maxGen">
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
            <option>6</option>
            <option>7</option>
            <option>8</option>
            <option>9</option>
        </select> generations.
    </form>
    <table class="pedigree max-gen-<?= $maxGen ?>">
        <tr>
            <?= $this->partial('partial/pedigree-cell', ['dog' => $dog, 'gen' => 0, 'maxGen' => $maxGen, 'n' => 1]); ?>
        </tr>
    </table>
</div>

<script>
    $(function() {
        $('#maxGen').change(function() {
            this.form.submit();
        }).val(<?= $maxGen ?>);
    });
</script>