<?php $this->headLink()
    ->prependStylesheet($this->basePath('css/ace-pedigree.print.css'), 'print')
    ->prependStylesheet($this->basePath('css/ace-pedigree.css'), 'screen, print'); ?>
<h3>Analysis</h3>
<div class="container">
    Coefficient of Inbreeding (COI): <?= round(100 * $animal->getInbreedingCoefficient(), 2) ?>%<br />
    Relationionship Coefficient of Sire and Dam (RC): <?= round(100 * $animal->getCoefficientOfRelationship(), 2) ?>%<br />
    Ancestor Loss (AVK): <?= round(100 * $animal->getAncestorLoss(), 2) ?>%<br />
    Mean Kinship with Population (MK): <?= round(100 * $animal->getAverageCovariance(), 2) ?>%<br />
    <?php if ($animal->getId()): ?>
    Relative Popularity as Ancestor (RP): <?= round(100 * $animal->getRelativePopularity(), 2) ?>%<br />
    <?php endif; ?>

    <small class="text-<?= $animal->getLastCompleteGen() < $maxGen ? 'danger' : 'success'; ?>">
        <i>Calculations based on <?= $animal->getLastCompleteGen() ?> complete generation(s) of <?= $maxGen ?> requested.</i>
    </small><br />

    <br />

    <table class="table table-striped ancestors">
        <thead>
            <tr>
                <th class="text-left">Total Contribution by Ancestor</th>
                <th style="width: 10%">Sex</th>
                <th style="width: 10%">Color</th>
                <th style="width: 10%">COI</th>
                <th style="width: 10%">Blood</th>
                <th style="width: 10%">Contrib</th>
                <th style="width: 5%">Total</th>
                <?php for ($gen = 1; $gen <= $maxGen; $gen++) : ?>
                    <th style="width: 5%">Gen <?= $gen ?></th>
                <?php endfor; ?>
            </tr>
        </thead>
        <tbody>
            <?php if (!count($animal->getUniqueAncestors())) : ?>
                <tr>
                    <td colspan="<?= 7 + $maxGen ?>" class="text-center">There are no ancestors to display.</td>
                </tr>
            <?php endif; ?>
            <?php foreach ($animal->getUniqueAncestors() as $ancestor) : ?>
                <?php if ($animal->getShortestPathTo($ancestor) > $maxGen) : continue; endif; ?>
                <tr>
                    <td class="text-left"><?= $this->entityLink($ancestor->getEntity()) ?></td>
                    <td><?= $ancestor->getEntity()->getSexDisplay() ?></td>
                    <td><?= $ancestor->getEntity()->getColor() ?></td>
                    <?= $ancestor->getInbreedingCoefficient() ? '<td>' : '<td class="text-secondary">' ?><?= round(100 * $ancestor->getInbreedingCoefficient(), 2) ?>%</td>
                    <?= 0 > 1 ? '<td>' : '<td class="text-secondary">' ?><?= round(100 * $animal->getConsanguinityWith($ancestor), 2) ?>%</td>
                    <?= $animal->getInbreedingContributionFrom($ancestor) ? '<td>' : '<td class="text-secondary">' ?><?= round(100 * $animal->getInbreedingContributionFrom($ancestor), 2) ?>%</td>
                    <td><?= array_sum($animal->getGenerationTotalsFor($ancestor)) ?></td>
                    <?php for ($gen = 1; $gen <= $maxGen; $gen++) : ?>
                        <td><?= $animal->getGenerationTotalsFor($ancestor)[$gen] ?? 0 ?></td>
                    <?php endfor; ?>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>