<td class="gen-<?= $gen . (!$gen ? ' no-print' : '')?>" rowspan="<?= 1 << ($maxGen - $gen) ?>">
    <?php if ($animal) : ?>

    <?php if ($animal->getTitles()) : ?>
    <div class="small text-success text-capitalize"><?= $animal->getTitles() ?></div>
    <?php endif; ?>

    <b><?= $this->entityLink($animal) ?></b>

    <?php if ($animal->getColor() || $animal->getBirthYear()) : ?>
    <div class="small text-muted"><?= $animal->getColor() ?> <?= $animal->getBirthYear() ?></div>
    <?php endif; ?>

    <?php if ($animal->getBirthCountry() || $animal->getHomeCountry()) : ?>
    <div class="small text-muted">
        <?= $animal->getBirthCountry() ?>
        <?php if ($animal->getHomeCountry() && $animal->getHomeCountry() != $animal->getBirthCountry()) : ?>
        &xrarr; <?= $animal->getHomeCountry() ?>
        <?php endif; ?>
    </div>
    <?php endif; ?>

    <?php endif; ?>
</td>

<?php if ($gen < $maxGen) : ?>
<?= $this->partial('partial/pedigree-cell', ['animal' => ($animal ? $animal->getSire() : null), 'gen' => $gen + 1, 'maxGen' => $maxGen, 'n' => $n + 1]); ?>
<?= $this->partial('partial/pedigree-cell', ['animal' => ($animal ? $animal->getDam() : null), 'gen' => $gen + 1, 'maxGen' => $maxGen, 'n' => $n + (1 << ($maxGen - $gen))]); ?>
<?php elseif ($n < (2 << $maxGen) - 1): ?>
</tr>
<tr>
<?php endif; ?>