<h3>Analysis</h3>
<div class="container">
    Coefficient of Inbreeding (COI): <?= round(100 * $dog->getInbreedingCoefficient(), 2) ?>%<br />
    Relationionship Coefficient of Sire and Dam (RC): <?= round(100 * $dog->getCoefficientOfRelationship(), 2) ?>%<br />
    Ancestor Loss (AVK): <?= round(100 * $dog->getAncestorLoss(), 2) ?>%<br />
    Mean Kinship with Population (MK): <?= round(100 * $dog->getAverageCovariance(), 2) ?>%<br />

    <small class="text-<?= $dog->getLastCompleteGen() < $maxGen ? 'danger' : 'success'; ?>">
        <i>Calculations based on <?= $dog->getLastCompleteGen() ?> complete generation(s) of <?= $maxGen ?> requested.</i>
    </small><br />

    <br />

    <table class="table table-striped ancestors">
        <thead>
            <tr>
                <th class="text-left">Total Contribution by Ancestor</th>
                <th style="width: 15%">Sex</th>
                <th style="width: 10%">COI</th>
                <th style="width: 10%">Blood</th>
                <th style="width: 10%">Contrib</th>
                <th style="width: 5%">Total</th>
                <?php for ($gen = 1; $gen <= $maxGen; $gen++) : ?>
                    <th style="width: 5%">Gen <?= $gen ?></th>
                <?php endfor; ?>
            </tr>
        </thead>
        <tbody>
            <?php if (!count($dog->getUniqueAncestors())) : ?>
                <tr>
                    <td colspan="<?= 6 + $maxGen ?>" class="text-center">There are no ancestors to display.</td>
                </tr>
            <?php endif; ?>
            <?php foreach ($dog->getUniqueAncestors() as $ancestor) : ?>
                <?php if ($dog->getShortestPathTo($ancestor) > $maxGen) : continue; endif; ?>
                <tr>
                    <td class="text-left"><?= $this->entityLink($ancestor->getEntity()) ?></td>
                    <td><?= $ancestor->getEntity()->getSexDisplay() ?></td>
                    <?= $ancestor->getInbreedingCoefficient() ? '<td>' : '<td class="text-secondary">' ?><?= round(100 * $ancestor->getInbreedingCoefficient(), 2) ?>%</td>
                    <?= 0 > 1 ? '<td>' : '<td class="text-secondary">' ?><?= round(100 * $dog->getConsanguinityWith($ancestor), 2) ?>%</td>
                    <?= $dog->getInbreedingContributionFrom($ancestor) ? '<td>' : '<td class="text-secondary">' ?><?= round(100 * $dog->getInbreedingContributionFrom($ancestor), 2) ?>%</td>
                    <td><?= array_sum($dog->getGenerationTotalsFor($ancestor)) ?></td>
                    <?php for ($gen = 1; $gen <= $maxGen; $gen++) : ?>
                        <td><?= $dog->getGenerationTotalsFor($ancestor)[$gen] ?? 0 ?></td>
                    <?php endfor; ?>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>