<?php $title = 'Population Relationship Graph'; ?>
<?php $this->headLink()->prependStylesheet($this->basePath('css/ace-pedigree.css'), 'screen, print'); ?>
<?php $this->headScript()
    ->appendFile('//unpkg.com/d3-dsv')
    ->appendFile('//unpkg.com/3d-force-graph')
    ->appendFile($this->basePath('js/ace-pedigree.js')); ?>
<?php $this->headTitle($title); ?>
<h2 class="page-header"><?= $title ?></h2>

<div id="kinship-graph" class="jumbotron"></div>

<script>
    $(function() {
        $('#kinship-graph').kinshipGraph('<?= $this->url('ace-pedigree/statistics', ['action' => 'population-data']) ?>');
    });
</script>