<?php $title = 'Recent Updates'; ?>
<?php $this->headTitle($title); ?>
<h2 class="page-header"><?= $title ?></h2>

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Animal</th>
                <th style="width: 15%">Updated</th>
            </tr>
        </thead>
        <tbody>
            <?php if (!count($animals)) : ?>
                <tr>
                    <td colspan="2" class="text-center">There are no animals to display.</td>
                </tr>
            <?php endif; ?>
            <?php foreach ($animals as $entity) : ?>
                <tr>
                    <td><?= $this->entityLink($entity) ?></td>
                    <td><?= $entity->getUpdatedAt()->format('Y-m-d H:i:s') ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Person</th>
                <th style="width: 15%">Updated</th>
            </tr>
        </thead>
        <tbody>
            <?php if (!count($persons)) : ?>
                <tr>
                    <td colspan="2" class="text-center">There are no persons to display.</td>
                </tr>
            <?php endif; ?>
            <?php foreach ($persons as $entity) : ?>
                <tr>
                    <td><?= $this->entityLink($entity) ?></td>
                    <td><?= $entity->getUpdatedAt()->format('Y-m-d H:i:s') ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>