<?php $title = 'Test Mating' . ($entity->getSire() && $entity->getDam() ? ': ' . $entity->getSire() . ' x ' . $entity->getDam() : ''); ?>
<?php $this->headLink()->appendStylesheet('/css/pedigree.css'); ?>
<?php $this->headTitle($title); ?>
<?php $this->pedigree($entity, $maxGen); ?>
<h2 class="page-header"><?= $title ?></h2>

<?= $this->pedigree() ?>

<?php if ($entity->getSire() && $entity->getDam()) : ?>
<?= $this->pedigree()->analysis() ?>
<?php endif; ?>