<?= $this->doctype() ?>

<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle($entity)->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/ace-pedigree.print.css'), 'screen, print')
        ->prependStylesheet($this->basePath('css/ace-pedigree.css'), 'screen, print')
        ->prependStylesheet('https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css', 'screen, print')
    ?>

    <?= $this->headScript()
            ->prependFile('https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js')
            ->prependFile('https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js')
            ->prependFile('https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js')
    ?>
</head>

<body onload="window.print()">
    <div class="container">
        <table>
            <thead>
                <tr>
                    <th>
                        <h2 class="page-header"><?= $entity ?></h2>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <div class="no-break">
                            <?= $this->pedigree($entity, $maxGen) ?>
                        </div>
                        <div class="no-break">
                            <?= $this->pedigree()->analysis() ?>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</body>

</html>