<?= $this->doctype() ?>

<html lang="en">
    <meta charset="utf-8">
    <?= $this->headTitle($entity)->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?= $this->headLink()
        ->prependStylesheet($this->basePath('css/print.css'), 'screen, print')
        ->prependStylesheet($this->basePath('css/pedigree.css'), 'screen, print')
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'), 'screen, print')
    ?>

    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
    ?>

    <body onload="window.print()">
        <div class="container">
            <h2 class="page-header"><?= $entity ?></h2>
            <?= $this->pedigree($entity, $maxGen) ?>
            <?= $this->pedigree()->analysis() ?>
        </div>
    </body>

</html>
