<?= $this->doctype() ?>

<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle($entity)->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/print.css'), 'screen, print')
        ->prependStylesheet($this->basePath('css/pedigree.css'), 'screen, print')
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'), 'screen, print')
    ?>

    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
    ?>
</head>

<body onload="window.print()">
    <div class="container">
        <table>
            <thead>
                <tr>
                    <th>
                        <h2 class="page-header"><?= $entity ?></h2>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <div class="no-break">
                            <?= $this->pedigree($entity, $maxGen) ?>
                        </div>
                        <div class="no-break">
                            <?= $this->pedigree()->analysis() ?>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</body>

</html>