<?php $this->navigation('navigation')
    ->findOneBy('route', 'ace-pedigree/animals')
    ->addPage([
        'label'  => 'View',
        'uri'    => '#',
        'active' => true,
        'class'  => 'hidden-nav',
    ]); ?>
<?php $this->headTitle($entity); ?>
<?php $this->pedigree($entity, $maxGen); ?>
<h2 class="page-header"><?= $entity ?></h2>

<div class="container">
    <h3>Details</h3>
    <div class="row row-no-gutters">
        <div class="col-sm-4">
            <table class="table table-condensed table-hover">
                <tbody>
                    <tr>
                        <th>Name</th>
                        <td><?= $entity->getName() ?></td>
                    </tr>
                    <tr>
                        <th>Call Name</th>
                        <td><?= $entity->getCallName() ?></td>
                    </tr>
                    <tr>
                        <th>Registration</th>
                        <td><?= $entity->getRegistration() ?></td>
                    </tr>
                    <tr>
                        <th>Breeder(s)</th>
                        <td>
                            <?php foreach ($entity->getBreeders() as $person) : ?>
                            <?= $this->entityLink($person) ?>
                            <?php endforeach; ?>
                        </td>
                    </tr>
                    <tr>
                        <th>Owner(s)</th>
                        <td>
                            <?php foreach ($entity->getOwners() as $person) : ?>
                            <?= $this->entityLink($person) ?>
                            <?php endforeach; ?>
                        </td>
                    </tr>
                    <tr>
                        <th><?= AcePedigree\HOUSE_SINGULAR ?></th>
                        <td><?= $entity->getHouse() ?></td>
                    </tr>
                    <tr>
                        <th>Sire</th>
                        <td><?= $this->entityLink($entity->getSire()) ?></td>
                    </tr>
                    <tr>
                        <th>Dam</th>
                        <td><?= $this->entityLink($entity->getDam()) ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-sm-4">
            <table class="table table-condensed table-hover">
                <tbody>
                    <tr>
                        <th>Sex</th>
                        <td><?= $entity->getSexDisplay() ?></td>
                    </tr>
                    <tr>
                        <th>Color</th>
                        <td><?= $entity->getColor() ?></td>
                    </tr>
                    <tr>
                        <th>Date of Birth</th>
                        <td><?= $this->fuzzyDate($entity->getBirthYear(), $entity->getBirthMonth(), $entity->getBirthDay()) ?></td>
                    </tr>
                    <tr>
                        <th>Date of Death</th>
                        <td><?= $this->fuzzyDate($entity->getDeathYear(), $entity->getDeathMonth(), $entity->getDeathDay()) ?></td>
                    </tr>
                    <tr>
                        <th>Land of Birth</th>
                        <td><?= $entity->getBirthCountry() ?></td>
                    </tr>
                    <tr>
                        <th>Land of Standing</th>
                        <td><?= $entity->getHomeCountry() ?></td>
                    </tr>
                    <tr>
                        <th>Height</th>
                        <td><?= $entity->getHeight() ?></td>
                    </tr>
                    <tr>
                        <th>Weight</th>
                        <td><?= $entity->getWeight() ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-sm-4">
            <table class="table table-condensed table-hover">
                <tbody>
                    <tr>
                        <th>Titles</th>
                        <td><?= $entity->getTitles() ?></td>
                    </tr>
                    <tr>
                        <th>OFA</th>
                        <td><?= $this->ofaLink($entity->getOfaNumber()) ?></td>
                    </tr>
                    <tr>
                        <th>Notes</th>
                        <td><?= $entity->getNotes() ?></td>
                    </tr>

                    <?php if ($entity->getOffspringCount()) : ?>
                    <tr>
                        <th>Offspring</th>
                        <td>
                            <?php foreach ($entity->getOffspring() as $animal) : ?>
                            <?= $this->entityLink($animal) ?><br />
                            <?php endforeach; ?>
                        </td>
                    </tr>
                    <?php endif; ?>

                    <?php if (count($fullSiblings)) : ?>
                    <tr>
                        <th>Full Siblings</th>
                        <td>
                            <?php foreach ($fullSiblings as $animal) : ?>
                            <?= $this->entityLink($animal) ?><br />
                            <?php endforeach; ?>
                        </td>
                    </tr>
                    <?php endif; ?>

                    <?php if (count($sireHalfSiblings)) : ?>
                    <tr>
                        <th>Half Siblings (Sire)</th>
                        <td>
                            <?php foreach ($sireHalfSiblings as $animal) : ?>
                            <?= $this->entityLink($animal) ?><br />
                            <?php endforeach; ?>
                        </td>
                    </tr>
                    <?php endif; ?>

                    <?php if (count($damHalfSiblings)) : ?>
                    <tr>
                        <th>Half Siblings (Dam)</th>
                        <td>
                            <?php foreach ($damHalfSiblings as $animal) : ?>
                            <?= $this->entityLink($animal) ?><br />
                            <?php endforeach; ?>
                        </td>
                    </tr>
                    <?php endif; ?>

                </tbody>
            </table>

            <div class="text-center no-print">
                <?= $this->testMatingButton($entity) ?>
                <?= $this->printButton($entity) ?>
            </div>
        </div>
    </div>
</div>

<div class="no-break">
    <?= $this->pedigree() ?>
</div>

<div class="no-break">
    <?= $this->pedigree()->analysis() ?>
</div>