<?php $title = 'Search Persons'; ?>
<?php $this->headTitle($title); ?>
<h2 class="page-header"><?= $title ?></h2>

<?= $this->form($form->setAttribute('action', $this->url('ace-pedigree/persons'))) ?>

<script>
    $(function() {
        $('form').submit(function() {
            $(this).find(':input').filter(function() {
                return $(this).val() === '';
            }).removeAttr('name');
            return true;
        });
    });
</script>