<?php $this->navigation('navigation')
    ->findOneBy('route', 'ace-pedigree/persons')
    ->addPage([
        'label'  => 'View',
        'uri'    => '#',
        'active' => true,
        'class'  => 'hidden-nav',
    ]); ?>
<?php $this->headTitle($entity); ?>
<h2 class="page-header"><?= $entity ?></h2>

<div class="container">
    <div class="row row-no-gutters">
        <div class="col-sm-4">
            <table class="table table-condensed table-hover">
                <tbody>
                    <tr>
                        <th>Name</th>
                        <td><?= $entity->getName() ?></td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>
                            <?php if ($entity->getEmail()) : ?>
                                <a href="mailto:<?= $entity->getEmail() ?>" target="_blank"><?= $entity->getEmail() ?></a>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <th>Website</th>
                        <td>
                            <?php if ($entity->getWebsite()) : ?>
                                <a href="<?= $entity->getWebsite() ?>" target="_blank"><?= $entity->getWebsite() ?></a>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <th>Phone</th>
                        <td><?= $entity->getPhone() ?></td>
                    </tr>
                    <tr>
                        <th>Address</th>
                        <td><?= $entity->getAddress() ?></td>
                    </tr>
                    <tr>
                        <th>Country</th>
                        <td><?= $entity->getCountry() ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <?php if (count($entity->getAnimalsBred())) : ?>
            <div class="col-sm-4">
                <table class="table table-condensed">
                    <tbody>
                        <tr>
                            <th>Breeder Of</th>
                            <td>
                                <?php foreach ($entity->getAnimalsBred() as $animal) : ?>
                                    <?= $this->entityLink($animal) ?><br />
                                <?php endforeach; ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        <?php endif; ?>
        <?php if (count($entity->getAnimalsOwned())) : ?>
            <div class="col-sm-4">
                <table class="table table-condensed">
                    <tbody>
                        <tr>
                            <th>Owner Of</th>
                            <td>
                                <?php foreach ($entity->getAnimalsOwned() as $animal) : ?>
                                    <?= $this->entityLink($animal) ?><br />
                                <?php endforeach; ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        <?php endif; ?>
    </div>
</div>